# Задача регрессии

In [88]:
import pandas as pd
import numpy as np

from sklearn.metrics import r2_score
from sklearn import linear_model
from geopy.distance import vincenty
from sklearn.preprocessing import MinMaxScaler, StandardScaler, PolynomialFeatures

# Подготовка данных
## Интеграция данных

In [57]:
df_vacancy = pd.read_csv('hh_vacancy.csv')
df_vacancy = df_vacancy.drop_duplicates('id')
df_vacancy

,id,area_id,area_name,employer_id,employment_id,employment_name,experience_id,experience_name,key_skills,name,published_at,salary_currency,salary_from,salary_to,schedule_id,schedule_name,specialization_id,specialization_name
0,25607531,1,Москва,1747017.0,full,Полная занятость,between3And6,От 3 до 6 лет,"PHP, Symfony, PostgreSQL, Redis, Design Patter...",Senior/Middle PHP-Developer,2018-05-06T17:43:45+0300,RUR,120000.0,170000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
1,25435136,1,Москва,553714.0,project,Проектная работа,between3And6,От 3 до 6 лет,NaN,Ведущий фронтенд-разработчик,2018-05-05T14:43:01+0300,NaN,NaN,NaN,remote,Удаленная работа,1,"Информационные технологии, интернет, телеком"
2,25284500,84,Ставрополь,5402.0,full,Полная занятость,between3And6,От 3 до 6 лет,"JavaScript, HTML5, CSS3, AngularJS, Bootstrap",Frontend-разработчик,2018-05-04T09:24:18+0300,RUR,60000.0,80000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
3,25641559,1,Москва,1554.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"1С программирование, 1С: Бухгалтерия, 1С Управ...",Программист-консультант 1С,2018-05-06T10:49:05+0300,NaN,NaN,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
4,25527035,2,Санкт-Петербург,3289100.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Менеджер по продажам,2018-05-05T16:15:16+0300,RUR,35000.0,100000.0,flexible,Гибкий график,1,"Информационные технологии, интернет, телеком"
5,25178591,1,Москва,2353123.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Системный аналитик,2018-05-07T00:54:39+0300,NaN,NaN,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
6,25449125,1,Москва,934019.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Java-разработчик,2018-05-06T11:41:28+0300,RUR,120000.0,220000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
7,25459894,1,Москва,1053428.0,full,Полная занятость,between3And6,От 3 до 6 лет,"Linux, AWS, Proxmox, Vagrant, Docker, Админист...",Системный администратор (DevOps),2018-05-06T17:00:04+0300,RUR,100000.0,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
8,25041175,2,Санкт-Петербург,934019.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Java разработчик (middle/senior),2018-05-05T18:43:16+0300,RUR,120000.0,220000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
9,25295125,78,Самара,2618807.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"Коммуникабельность, Аналитический склад ума, Н...",Менеджер по работе с корпоративными клиентами,2018-05-06T11:45:27+0300,RUR,35000.0,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
10,25446129,1,Москва,1300820.0,full,Полная занятость,between3And6,От 3 до 6 лет,"SCALA, Java, Spark, NoSQL, Big Data",Senior Java/Scala developer (BigData),2018-05-06T08:21:43+0300,NaN,NaN,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
11,25632259,2,Санкт-Петербург,2470951.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"PHP, Yii2, PostgreSQL, ООП",PHP Developer / Разработчик PHP,2018-05-05T16:25:43+0300,RUR,110000.0,NaN,remote,Удаленная работа,1,"Информационные технологии, интернет, телеком"
12,25595230,1,Москва,2700524.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"1С программирование, 1С: Бухгалтерия, 1С: Пред...",Программист 1С,2018-05-06T09:30:12+0300,RUR,80000.0,100000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
13,25534356,72,Пермь,1931419.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"PHP, Atlassian Jira, Git, MySQL, Yii, Symfony,...",Backend-разработчик,2018-05-06T09:07:45+0300,RUR,30000.0,90000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
14,25416786,69,Орел,2253456.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"Информационные технологии, Информационная безо...",Руководитель технического отдела / Team Lead,2018-05-05T23:55:10+0300,RUR,NaN,70000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
15,25337548,1,Москва,2942396.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"Java EE, JavaScript, Java SE, SQL, jQuery, Jav...",Java-разработчик,2018-05-05T11:29:27+0300,NaN,NaN,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
16,24665195,1,Москва,656166.0,full,Полная занятость,between3And6,От 3 до 6 лет,"JavaScript, REST, jQuery, CSS, HTML, Git, Рабо...",Ведущий разработчик Frontend / Frontend Develo...,2018-05-04T11:13:51+0300,RUR,160000.0,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
17,25341043,4,Новосибирск,913002.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"Администрирование серверов Linux, Техническая ...",Администратор Linux (DevOps),2018-05-05T13:38:07+0300,NaN,NaN,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
18,25469872,1,Москва,1747017.0,full,Полная занятость,between3And6,От 3 до 6 лет,"HTML, CSS, JavaScript, jQuery, Mercurial, Git,...",Frontend-Developer React,2018-05-04T10:36:17+0300,RUR,100000.0,170000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
19,25531733,2,Санкт-Петербург,1577832.0,full,Полная занятость,between3And6,От 3 до 6 лет,"QA, Регресионное тестирование, Linux, Scrum, A...",QA Lead / Ведущий специалист по тестированию,2018-05-06T01:08:25+0300,NaN,NaN,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
20,25531764,2,Санкт-Петербург,1577832.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"CRM, zendesk, Консультирование клиентов, Техни...",Специалист поддержки клиентов,2018-05-06T02:18:02+0300,RUR,60000.0,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
21,25526867,1,Москва,2276869.0,full,Полная занятость,between3And6,От 3 до 6 лет,"C++, Lua, проектирование печатных плат",Инженер-электронщик микроконтроллеров,2018-05-05T16:11:18+0300,NaN,NaN,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
22,25512336,26,Воронеж,748699.0,full,Полная занятость,noExperience,Нет опыта,NaN,Программист 1С (программист-стажер 1С),2018-05-05T09:53:09+0300,RUR,20000.0,30000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
23,25578876,1,Москва,5402.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Аналитик внедрения информационных систем,2018-05-05T11:43:40+0300,RUR,80000.0,100000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
24,25662140,2,Санкт-Петербург,745841.0,full,Полная занятость,noExperience,Нет опыта,"QA, Junior, Mobile development, Web developmen...",Junior QA,2018-05-04T09:58:44+0300,USD,800.0,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
25,25582544,1,Москва,934019.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Ведущий программист 1C,2018-05-05T13:33:42+0300,RUR,100000.0,190000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
26,25528387,88,Казань,913233.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Тестировщик ПО,2018-05-05T16:57:45+0300,RUR,30000.0,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
27,23572477,2,Санкт-Петербург,1573351.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"Java, Spring Framework",Java Developer,2018-05-04T17:26:45+0300,NaN,NaN,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
28,25422324,2,Санкт-Петербург,1054705.0,full,Полная занятость,noExperience,Нет опыта,NaN,Консультант по внедрению и сопровождению 1С,2018-05-05T08:38:02+0300,NaN,NaN,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
29,25486171,2,Санкт-Петербург,588914.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,"Senior Backend Developer (Python, Golang)",2018-05-04T22:31:11+0300,RUR,110000.0,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19807,25617656,1,Москва,816.0,full,Полная занятость,moreThan6,Более 6 лет,NaN,Специалист тендерного отдела (внутренние закупки),2018-05-04T13:05:12+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19808,25407542,1,Москва,816.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Product manager (Oracle),2018-04-23T11:11:03+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19809,25440649,1,Москва,1520642.0,full,Полная занятость,noExperience,Нет опыта,"внимательность, Грамотность",Специалист тендерного отдела,2018-04-17T18:58:33+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19810,25103683,23,Владимир,665467.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Ведущий специалист по обучению (услуги по обуч...,2018-04-23T15:29:18+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19811,24983215,53,Краснодар,2118134.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Специалист по закупкам,2018-05-03T08:47:33+0300,RUR,25000.0,30000.0,fullDay,Полный день,26,Закупки
19812,25534620,68,Омск,1006743.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Специалист по закупкам ( 44 ФЗ),2018-04-24T09:17:36+0300,RUR,20000.0,NaN,fullDay,Полный день,26,Закупки
19813,25523145,1374,Нефтеюганск,197135.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Ведущий специалист сектора развития и планиров...,2018-04-23T14:19:22+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19814,25437016,72,Пермь,1597934.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"Закупки, Ведение переговоров, Управление прода...",Менеджер по снабжению,2018-04-17T15:45:34+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19815,25493475,92,Тула,1059553.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Специалист по закупкам,2018-04-20T11:58:52+0300,RUR,28000.0,NaN,fullDay,Полный день,26,Закупки
19816,25369879,1,Москва,2828754.0,full,Полная занятость,noExperience,Нет опыта,"MS Excel, MS Word, 1С: Бухгалтерия, CRM",Менеджер по закупкам и работе с партнерами,2018-05-06T17:50:39+0300,RUR,40000.0,65000.0,fullDay,Полный день,26,Закупки
19817,25044639,1,Москва,3177.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Менеджер по закупкам,2018-04-19T13:44:24+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19818,25365987,1,Москва,725989.0,full,Полная занятость,between3And6,От 3 до 6 лет,"Английский язык, SAP, Логистика",Специалист по логистике и закупкам,2018-04-16T13:32:38+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19819,25300707,1,Москва,2629400.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"ВЭД, Закупки, Логистика поставок, Ведение пере...",Менеджер по закупкам,2018-05-06T14:30:16+0300,RUR,80000.0,100000.0,fullDay,Полный день,26,Закупки
19820,25373606,1,Москва,7040.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Менеджер по закупкам,2018-05-04T08:51:07+0300,RUR,60000.0,NaN,fullDay,Полный день,26,Закупки
19821,25253240,1,Москва,816.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Ассистент отдела закупок/Ассистент менеджера п...,2018-05-04T13:07:42+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19822,25285315,1,Москва,816.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Специалист по закупкам ( IT-оборудование),2018-05-04T13:07:28+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19823,25387839,1,Москва,4526.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Ведущий менеджер по продуктам и закупкам,2018-04-25T14:52:29+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19824,25488505,112,Ярославль,67611.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Менеджер по сопровождению торгов,2018-04-20T08:58:00+0300,RUR,28000.0,35000.0,fullDay,Полный день,26,Закупки
19825,25257683,1204,Бердск,2622312.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Менеджер по снабжению,2018-05-02T19:17:02+0300,RUR,30000.0,40000.0,fullDay,Полный день,26,Закупки
19826,25503951,1,Москва,597423.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Менеджер по закупкам/Purchase manager,2018-05-06T09:44:00+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19827,25326612,1,Москва,2592107.0,full,Полная занятость,between3And6,От 3 до 6 лет,"Category Management, Категорийный менеджмент, ...",Category manager,2018-05-04T16:50:22+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19828,25602266,84,Ставрополь,876275.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Специалист отдела закупок / по выбору поставщиков,2018-05-06T09:03:04+0300,RUR,20000.0,25000.0,fullDay,Полный день,26,Закупки
19829,25603653,112,Ярославль,971924.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Менеджер по снабжению и закупкам,2018-05-03T08:14:04+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19830,25493705,1,Москва,12504.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Менеджер по закупкам,2018-05-05T12:07:20+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19831,25530892,61,Йошкар-Ола,2225569.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Няня,2018-04-23T19:30:15+0300,RUR,15000.0,NaN,flexible,Гибкий график,27,Домашний персонал
19832,25292524,49,Киров,1671906.0,part,Частичная занятость,between1And3,От 1 года до 3 лет,NaN,Домработница/домработник,2018-04-09T10:32:52+0300,NaN,NaN,NaN,flexible,Гибкий график,27,Домашний персонал
19833,25684255,81,Южно-Сахалинск,19602.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"Монтаж оборудования, Монтаж инженерных систем,...",Монтажник оборудования связи,2018-05-07T03:22:41+0300,RUR,NaN,50000.0,fullDay,Полный день,29,Рабочий персонал
19834,25684252,102,Хабаровск,19602.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"Монтаж оборудования, Производство строительно-...",Монтажник оборудования связи,2018-05-07T03:19:22+0300,NaN,NaN,NaN,fullDay,Полный день,29,Рабочий персонал
19835,25608185,2,Санкт-Петербург,84585.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Грузчик-техник,2018-04-27T18:43:02+0300,RUR,45000.0,NaN,fullDay,Полный день,29,Рабочий персонал
19836,25086936,24,Волгоград,967438.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Приборист (6 разряд),2018-04-25T09:07:10+0300,NaN,NaN,NaN,fullDay,Полный день,29,Рабочий персонал

In [58]:
df_vacancy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19837 entries, 0 to 19836
Data columns (total 18 columns):
id                     19837 non-null int64
area_id                19837 non-null int64
area_name              19837 non-null object
employer_id            19813 non-null float64
employment_id          19805 non-null object
employment_name        19805 non-null object
experience_id          19805 non-null object
experience_name        19805 non-null object
key_skills             6654 non-null object
name                   19837 non-null object
published_at           19837 non-null object
salary_currency        10358 non-null object
salary_from            9611 non-null float64
salary_to              4594 non-null float64
schedule_id            19805 non-null object
schedule_name          19805 non-null object
specialization_id      19837 non-null int64
specialization_name    19837 non-null object
dtypes: float64(3), int64(3), object(12)
memory usage: 2.9+ MB

In [59]:
# Разделение на обучающую и тестовую выборку по id, который соответствует порядку добавления вакаансий на сайт.
count_df = len(df_vacancy)
df_vacancy.sort_values(by='id', ascending=True, inplace=True)
df_vacancy_test = df_vacancy[int(2*count_df/3):]
df_vacancy_train = df_vacancy[:int(2*count_df/3)]

In [60]:
# Удаление записей с пропущенными значениями NaN.
def df_clean_nan_id(df):
    return df[np.isfinite(df['salary_from']) & 
              np.isfinite(df['area_id']) & 
              np.isfinite(df['employer_id']) &
              np.isfinite(df['specialization_id'])]

df_vacancy_train = df_clean_nan_id(df_vacancy_train)

In [61]:
# Таблица с компаниями.
df_company = pd.read_csv('hh_company.csv')
df_company = df_company.drop_duplicates('employer_id')
df_company.head(2)

,employer_id,employer_name,employer_site,industry_id,industry_name
0,1747017.0,Колтач Солюшнс,NaN,7,"Информационные технологии, системная интеграци..."
1,553714.0,Нотамедиа,NaN,7,"Информационные технологии, системная интеграци..."

In [62]:
# Объдединение вакансий с компаниями.
def df_merge_vacancy(df):
    return pd.merge(df, df_company, on='employer_id')

df_vacancy_train = df_merge_vacancy(df_vacancy_train)
df_vacancy_train.head(2)

,id,area_id,area_name,employer_id,employment_id,employment_name,experience_id,experience_name,key_skills,name,...,salary_from,salary_to,schedule_id,schedule_name,specialization_id,specialization_name,employer_name,employer_site,industry_id,industry_name
0,7160726,2,Санкт-Петербург,558625.0,part,Частичная занятость,noExperience,Нет опыта,NaN,Оператор call-центра,...,35000.0,NaN,flexible,Гибкий график,3,"Маркетинг, реклама, PR",Cистема Северо-Запад,NaN,7,"Информационные технологии, системная интеграци..."
1,7296077,67,Великий Новгород,558625.0,full,Полная занятость,noExperience,Нет опыта,NaN,Специалист отдела продаж,...,30000.0,60000.0,fullDay,Полный день,17,Продажи,Cистема Северо-Запад,NaN,7,"Информационные технологии, системная интеграци..."

In [63]:
# Таблица с городами.
df_cities = pd.read_csv('cities.csv')
df_cities.head(2)

,Индекс,Тип региона,Регион,Тип района,Район,Тип города,Город,Тип н/п,Н/п,Код КЛАДР,...,Уровень по ФИАС,Признак центра района или региона,Код ОКАТО,Код ОКТМО,Код ИФНС,Часовой пояс,Широта,Долгота,Федеральный округ,Население
0,385200.0,Респ,Адыгея,NaN,NaN,г,Адыгейск,NaN,NaN,100000200000,...,4: город,0,79403000000,7.970300e+10,107,UTC+3,44.878372,39.190172,Южный,12689.0
1,385000.0,Респ,Адыгея,NaN,NaN,г,Майкоп,NaN,NaN,100000100000,...,4: город,2,79401000000,7.970100e+10,105,UTC+3,44.609827,40.100653,Южный,144055.0

In [64]:
# Формированеи признаков для городов.
df_cities = df_cities[['Город','Широта','Долгота','Население', 'Регион']]
df_cities['Город'] = df_cities.apply(lambda row: row['Регион']
                                     if type(row['Город']) != str and np.isnan(row['Город'])
                                     else row['Город'], axis=1)
df_cities = df_cities[['Город','Широта','Долгота','Население']]
df_cities = df_cities.rename(index=str, columns={"Город": "area_name"})
df_cities = df_cities.rename(index=str, columns={"Широта": "latitude"})
df_cities = df_cities.rename(index=str, columns={"Долгота": "longitude"})
df_cities = df_cities.rename(index=str, columns={"Население": "population"})
df_cities['population'].fillna((df_cities['population'].mean()), inplace=True)
moscow_latitude, moscow_longitude = list(df_cities.loc[df_cities.area_name == 'Москва'][['latitude','longitude']].iloc[0])
df_cities['distance_to_Moscow'] = df_cities.apply(lambda row: vincenty((moscow_latitude, moscow_longitude),
                                                                       (row.latitude, row.longitude)).kilometers, axis=1)
df_cities.head(2)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: DeprecationWarning:

Vincenty is deprecated and is going to be removed in geopy 2.0. Use `geopy.distance.geodesic` (or the default `geopy.distance.distance`) instead, which is more accurate and always converges.

  area_name   latitude  longitude  population  distance_to_Moscow
0  Адыгейск  44.878372  39.190172     12689.0         1214.804843
1    Майкоп  44.609827  40.100653    144055.0         1251.957644

In [65]:
# Объдединение вакансий с городами.
def df_merge_city(df):
    return pd.merge(df, df_cities, on='area_name')

df_vacancy_train = df_merge_city(df_vacancy_train)
df_vacancy_train.head(2)

,id,area_id,area_name,employer_id,employment_id,employment_name,experience_id,experience_name,key_skills,name,...,specialization_id,specialization_name,employer_name,employer_site,industry_id,industry_name,latitude,longitude,population,distance_to_Moscow
0,7160726,2,Санкт-Петербург,558625.0,part,Частичная занятость,noExperience,Нет опыта,NaN,Оператор call-центра,...,3,"Маркетинг, реклама, PR",Cистема Северо-Запад,NaN,7,"Информационные технологии, системная интеграци...",59.939125,30.315822,4848742.0,636.038853
1,10161653,2,Санкт-Петербург,558625.0,full,Полная занятость,noExperience,Нет опыта,NaN,Менеджер call-центра,...,17,Продажи,Cистема Северо-Запад,NaN,7,"Информационные технологии, системная интеграци...",59.939125,30.315822,4848742.0,636.038853

In [66]:
#Приводим к одной валюте
def convert_valute_to_rub(salary, currency):
    if currency == 'USD':
        return salary*65.58
    elif currency == 'EUR':
        return salary*73.66
    elif currency == 'UAH':
        return salary*2.41
    return salary

def df_convert_valute(df):
    df['salary_from'] = df.apply(lambda row: convert_valute_to_rub(row.salary_from, row.salary_currency), axis=1)
    return df

print(df_vacancy_train['salary_currency'].unique())
df_vacancy_train = df_convert_valute(df_vacancy_train)

['RUR' 'EUR' 'USD' 'UAH']

## Формирование признаков

In [67]:
# Добавление информации о кол-ве ключевых навыков вакансии.
def df_add_key_skills_count(df):
    df['key_skills_count'] = df.apply(lambda row:0 if type(row.key_skills) == float
                                      else row.key_skills.count(',') + 1, axis=1)
    return df

df_vacancy_train = df_add_key_skills_count(df_vacancy_train)
df_vacancy_train['key_skills_count'].describe()

count    6186.000000
mean        2.503556
std         4.532688
min         0.000000
25%         0.000000
50%         0.000000
75%         4.000000
max        30.000000
Name: key_skills_count, dtype: float64

### One Hot Encoding

In [68]:
def one_hot_encode(df, df_train):
    categorical_columns = [
        'employment_name',
        'experience_name',
        'salary_currency',
        'schedule_name'
    ]
    for category in categorical_columns:
        for category_value in df_train[category].unique():
            df[f'{category}_is_{category_value}'] = (df[category] == category_value).astype(float)
    return df

df_vacancy_train = one_hot_encode(df_vacancy_train, df_vacancy_train)
df_vacancy_train.head(2)

,id,area_id,area_name,employer_id,employment_id,employment_name,experience_id,experience_name,key_skills,name,...,experience_name_is_Более 6 лет,salary_currency_is_RUR,salary_currency_is_EUR,salary_currency_is_USD,salary_currency_is_UAH,schedule_name_is_Гибкий график,schedule_name_is_Полный день,schedule_name_is_Сменный график,schedule_name_is_Удаленная работа,schedule_name_is_Вахтовый метод
0,7160726,2,Санкт-Петербург,558625.0,part,Частичная занятость,noExperience,Нет опыта,NaN,Оператор call-центра,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,10161653,2,Санкт-Петербург,558625.0,full,Полная занятость,noExperience,Нет опыта,NaN,Менеджер call-центра,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

### Target Encoding

In [69]:
areas = df_vacancy_train[['id', 'area_name']].\
        groupby(['area_name']).\
        agg({'id': 'count'}).\
        rename(columns={'id': 'area_vacancy_count'})
areas.head()

             area_vacancy_count
area_name
Абакан                        6
Агрыз                         2
Александров                   2
Алексин                       2
Альметьевск                  10

In [70]:
areas = df_vacancy_train[['salary_from', 'area_name']].\
        groupby(['area_name']).\
        agg({'salary_from': 'mean'}).\
        rename(columns={'salary_from': 'area_salary_mean'})
areas.head()

             area_salary_mean
area_name
Абакан           38166.666667
Агрыз            13500.000000
Александров      35000.000000
Алексин          39000.000000
Альметьевск      35200.000000

In [71]:
def target_encode_mean(df, df_train):
    categorical_columns = [
        'area_name',
        'employer_id',
        'employment_name',
        'experience_name',
        'salary_currency',
        'schedule_name'
    ]
    for category in categorical_columns:
        category_table = df_vacancy_train[['salary_from', category]].\
                            groupby([category]).\
                            agg({'salary_from': 'mean'}).\
                            rename(columns={'salary_from': f'{category}_salary_mean'})
        df = pd.merge(df, category_table, left_on=category, right_index=True)
    return df

def target_encode_count(df, df_train):
    categorical_columns = [
        'area_name',
        'employer_id',
        'employment_name',
        'experience_name',
        'salary_currency',
        'schedule_name'
    ]
    for category in categorical_columns:
        category_table = df_vacancy_train[['id', category]].\
                            groupby([category]).\
                            agg({'id': 'count'}).\
                            rename(columns={'id': f'{category}_id_count'})
        df = pd.merge(df, category_table, left_on=category, right_index=True)
    return df


df_vacancy_train = target_encode_mean(df_vacancy_train, df_vacancy_train)
df_vacancy_train = target_encode_count(df_vacancy_train, df_vacancy_train)
df_vacancy_train.head(2)

,id,area_id,area_name,employer_id,employment_id,employment_name,experience_id,experience_name,key_skills,name,...,employment_name_salary_mean,experience_name_salary_mean,salary_currency_salary_mean,schedule_name_salary_mean,area_name_id_count,employer_id_id_count,employment_name_id_count,experience_name_id_count,salary_currency_id_count,schedule_name_id_count
0,7160726,2,Санкт-Петербург,558625.0,part,Частичная занятость,noExperience,Нет опыта,NaN,Оператор call-центра,...,24043.493151,39471.266614,52531.193002,63035.525926,543,13,146,2543,6145,405
106,19356190,2,Санкт-Петербург,43410.0,part,Частичная занятость,noExperience,Нет опыта,NaN,Менеджер по продажам,...,24043.493151,39471.266614,52531.193002,63035.525926,543,57,146,2543,6145,405

### Дополнительные параметры

Уровень жизни
https://www.domofond.ru/statya/polnyy_reyting_gorodov_rossii_po_kachestvu_zhizni_v_2018_godu/7679
    
Рейтинг компаний
http://www.cnews.ru/reviews/rynok_it_itogi_2017/review_table/5ea292822e4f02a7c71a3495f1e456e5b320f86a

In [72]:
# code

In [73]:
# code

In [74]:
# code

### Выбор признаков

In [75]:
df_vacancy_train.columns

Index(['id', 'area_id', 'area_name', 'employer_id', 'employment_id',
       'employment_name', 'experience_id', 'experience_name', 'key_skills',
       'name', 'published_at', 'salary_currency', 'salary_from', 'salary_to',
       'schedule_id', 'schedule_name', 'specialization_id',
       'specialization_name', 'employer_name', 'employer_site', 'industry_id',
       'industry_name', 'latitude', 'longitude', 'population',
       'distance_to_Moscow', 'key_skills_count',
       'employment_name_is_Частичная занятость',
       'employment_name_is_Полная занятость', 'employment_name_is_Стажировка',
       'employment_name_is_Проектная работа', 'experience_name_is_Нет опыта',
       'experience_name_is_От 1 года до 3 лет',
       'experience_name_is_От 3 до 6 лет', 'experience_name_is_Более 6 лет',
       'salary_currency_is_RUR', 'salary_currency_is_EUR',
       'salary_currency_is_USD', 'salary_currency_is_UAH',
       'schedule_name_is_Гибкий график', 'schedule_name_is_Полный день',
       'schedule_name_is_Сменный график', 'schedule_name_is_Удаленная работа',
       'schedule_name_is_Вахтовый метод', 'area_name_salary_mean',
       'employer_id_salary_mean', 'employment_name_salary_mean',
       'experience_name_salary_mean', 'salary_currency_salary_mean',
       'schedule_name_salary_mean', 'area_name_id_count',
       'employer_id_id_count', 'employment_name_id_count',
       'experience_name_id_count', 'salary_currency_id_count',
       'schedule_name_id_count'],
      dtype='object')

In [76]:
train_y = df_vacancy_train['salary_from']
x_labels = ['latitude', 'longitude', 'population',
       'distance_to_Moscow', 'key_skills_count',
       'employment_name_is_Частичная занятость',
       'employment_name_is_Полная занятость', 'employment_name_is_Стажировка',
       'employment_name_is_Проектная работа', 'experience_name_is_Нет опыта',
       'experience_name_is_От 1 года до 3 лет',
       'experience_name_is_От 3 до 6 лет', 'experience_name_is_Более 6 лет',
       'salary_currency_is_RUR', 'salary_currency_is_EUR',
       'salary_currency_is_USD', 'salary_currency_is_UAH',
       'schedule_name_is_Гибкий график', 'schedule_name_is_Полный день',
       'schedule_name_is_Сменный график', 'schedule_name_is_Удаленная работа',
       'schedule_name_is_Вахтовый метод', 'area_name_salary_mean',
       'employer_id_salary_mean', 'employment_name_salary_mean',
       'experience_name_salary_mean', 'salary_currency_salary_mean',
       'schedule_name_salary_mean', 'area_name_id_count',
       'employer_id_id_count', 'employment_name_id_count',
       'experience_name_id_count', 'salary_currency_id_count',
       'schedule_name_id_count']
train_X = df_vacancy_train[x_labels]

### Нормализация

MinMaxScaler, StandardScaler

In [77]:
min_max_scaler = MinMaxScaler()
print(min_max_scaler.fit(train_X))
train_X = min_max_scaler.transform(train_X)

MinMaxScaler(copy=True, feature_range=(0, 1))

## Обучение линейной регрессии

In [78]:
reg = linear_model.LinearRegression()
reg.fit(train_X, train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [79]:
# Коэф. уравнения.
pd.DataFrame(list(zip(x_labels, reg.coef_)), columns = ['name', 'coef']).sort_values('coef', ascending=False)

                                      name          coef
6      employment_name_is_Полная занятость  1.363259e+17
17          schedule_name_is_Гибкий график  8.761313e+16
21         schedule_name_is_Вахтовый метод  8.717915e+16
8      employment_name_is_Проектная работа  6.100260e+16
5   employment_name_is_Частичная занятость  5.686568e+16
7            employment_name_is_Стажировка  5.358644e+16
19         schedule_name_is_Сменный график  5.227243e+16
33                  schedule_name_id_count  5.135090e+16
25             experience_name_salary_mean  4.356274e+16
20       schedule_name_is_Удаленная работа  4.354631e+16
18            schedule_name_is_Полный день  2.888015e+16
13                  salary_currency_is_RUR  1.562120e+16
26             salary_currency_salary_mean  8.910032e+15
15                  salary_currency_is_USD  4.264996e+15
16                  salary_currency_is_UAH  3.934698e+15
23                 employer_id_salary_mean  2.276960e+05
2                               population  5.016828e+04
22                   area_name_salary_mean  4.496800e+04
1                                longitude  1.899253e+04
29                    employer_id_id_count  1.068000e+04
4                         key_skills_count  5.338262e+03
0                                 latitude -7.581434e+03
3                       distance_to_Moscow -2.205663e+04
28                      area_name_id_count -5.710800e+04
14                  salary_currency_is_EUR -9.784143e+14
10   experience_name_is_От 1 года до 3 лет -7.332874e+15
32                salary_currency_id_count -7.705884e+15
9             experience_name_is_Нет опыта -1.181491e+16
24             employment_name_salary_mean -1.208046e+16
27               schedule_name_salary_mean -4.086457e+16
30                employment_name_id_count -7.065895e+16
11        experience_name_is_От 3 до 6 лет -1.652765e+17
31                experience_name_id_count -1.932233e+17
12          experience_name_is_Более 6 лет -2.390517e+17

### Оценка качества обучения

In [83]:
# Точность на обучающей выборке.
train_r2 = r2_score(train_y, reg.predict(train_X))
train_r2

0.7472275607200445

In [84]:
# Подготовка тестовой выборки.
df_vacancy_test = df_clean_nan_id(df_vacancy_test)
df_vacancy_test = df_merge_vacancy(df_vacancy_test)
df_vacancy_test = df_merge_city(df_vacancy_test)
df_vacancy_test = df_convert_valute(df_vacancy_test)
df_vacancy_test = df_add_key_skills_count(df_vacancy_test)
df_vacancy_test = one_hot_encode(df_vacancy_test, df_vacancy_train)
df_vacancy_test = target_encode_mean(df_vacancy_test, df_vacancy_train)
df_vacancy_test = target_encode_count(df_vacancy_test, df_vacancy_train)

In [85]:
test_y = df_vacancy_test['salary_from']
test_X = df_vacancy_test[x_labels]
test_X = min_max_scaler.transform(test_X)
# Точность на тестовой выборке.
test_r2 = r2_score(test_y, reg.predict(test_X))
test_r2

0.502046050847845

## Что еще?

Полиномилальная регрессия

    from sklearn.preprocessing import PolynomialFeatures

Алгоритм *k*-ближайших соседей

    from sklearn.neighbors import KNeighborsRegressor

In [89]:
# Точность на обучающей выборке.
quadratic = PolynomialFeatures(degree=2)
train_X_quad = quadratic.fit_transform(train_X)

reg = linear_model.LinearRegression()
reg = reg.fit(train_X_quad, train_y)
train_r2 = r2_score(train_y, reg.predict(train_X_quad))
train_r2

0.7867004017550059

In [91]:
pd.set_option('display.max_column',None)
pd.set_option('display.max_rows',None)
pd.set_option('display.max_seq_items',None)
pd.set_option('display.max_colwidth', 500)
pd.set_option('expand_frame_repr', True)

In [92]:
# Коэф. уравнения.
pd.DataFrame(list(zip(quadratic.get_feature_names(x_labels), reg.coef_)),
             columns = ['name', 'coef']).sort_values('coef', ascending=False)

,name,coef
313,experience_name_is_Нет опыта schedule_name_is_Гибкий график,2.968031e+17
329,experience_name_is_Нет опыта schedule_name_id_count,1.582952e+17
21,schedule_name_is_Удаленная работа,1.044328e+17
337,experience_name_is_От 1 года до 3 лет schedule_name_is_Гибкий график,8.513934e+16
626,experience_name_id_count schedule_name_id_count,8.201382e+16
245,employment_name_is_Полная занятость schedule_name_salary_mean,7.229652e+16
370,experience_name_is_От 3 до 6 лет schedule_name_salary_mean,7.089092e+16
507,schedule_name_is_Полный день experience_name_id_count,6.872389e+16
347,experience_name_is_От 1 года до 3 лет schedule_name_salary_mean,6.233356e+16
247,employment_name_is_Полная занятость employer_id_id_count,5.812028e+16
623,employment_name_id_count schedule_name_id_count,5.759763e+16
316,experience_name_is_Нет опыта schedule_name_is_Удаленная работа,5.683085e+16
419,salary_currency_is_RUR schedule_name_id_count,5.077741e+16
18,schedule_name_is_Гибкий график,4.985811e+16
510,schedule_name_is_Сменный график^2,4.832643e+16
405,salary_currency_is_RUR schedule_name_is_Сменный график,4.832643e+16
360,experience_name_is_От 3 до 6 лет schedule_name_is_Гибкий график,4.740411e+16
522,schedule_name_is_Сменный график experience_name_id_count,4.647127e+16
587,experience_name_salary_mean schedule_name_salary_mean,4.588779e+16
23,area_name_salary_mean,4.519401e+16
5,key_skills_count,4.416152e+16
529,schedule_name_is_Удаленная работа employment_name_salary_mean,4.266850e+16
403,salary_currency_is_RUR schedule_name_is_Гибкий график,4.260412e+16
106,population employment_name_is_Полная занятость,3.918860e+16
618,employer_id_id_count salary_currency_id_count,3.867419e+16
523,schedule_name_is_Сменный график salary_currency_id_count,3.809559e+16
20,schedule_name_is_Сменный график,3.799833e+16
602,schedule_name_salary_mean^2,3.793096e+16
590,experience_name_salary_mean employment_name_id_count,3.778401e+16
417,salary_currency_is_RUR experience_name_id_count,3.761822e+16
485,schedule_name_is_Гибкий график experience_name_salary_mean,3.723928e+16
125,population experience_name_salary_mean,3.610092e+16
131,population experience_name_id_count,3.562448e+16
34,schedule_name_id_count,3.477933e+16
4,distance_to_Moscow,3.466714e+16
603,schedule_name_salary_mean area_name_id_count,3.451257e+16
68,latitude schedule_name_id_count,3.368231e+16
521,schedule_name_is_Сменный график employment_name_id_count,3.335192e+16
608,schedule_name_salary_mean schedule_name_id_count,3.241901e+16
534,schedule_name_is_Удаленная работа employer_id_id_count,3.149384e+16
505,schedule_name_is_Полный день employer_id_id_count,2.940432e+16
520,schedule_name_is_Сменный график employer_id_id_count,2.918880e+16
7,employment_name_is_Полная занятость,2.823403e+16
30,employer_id_id_count,2.758252e+16
133,population schedule_name_id_count,2.757308e+16
363,experience_name_is_От 3 до 6 лет schedule_name_is_Удаленная работа,2.673401e+16
29,area_name_id_count,2.664365e+16
113,population salary_currency_is_RUR,2.652814e+16
508,schedule_name_is_Полный день salary_currency_id_count,2.650027e+16
32,experience_name_id_count,2.584384e+16
2,longitude,2.549241e+16
411,salary_currency_is_RUR experience_name_salary_mean,2.513493e+16
398,experience_name_is_Более 6 лет schedule_name_id_count,2.440830e+16
238,employment_name_is_Полная занятость schedule_name_is_Удаленная работа,2.350352e+16
236,employment_name_is_Полная занятость schedule_name_is_Полный день,2.323945e+16
625,experience_name_id_count salary_currency_id_count,2.302686e+16
375,experience_name_is_От 3 до 6 лет salary_currency_id_count,2.224794e+16
406,salary_currency_is_RUR schedule_name_is_Удаленная работа,2.186656e+16
289,employment_name_is_Проектная работа schedule_name_is_Полный день,2.128489e+16
351,experience_name_is_От 1 года до 3 лет experience_name_id_count,2.081658e+16
330,experience_name_is_От 1 года до 3 лет^2,2.081658e+16
127,population schedule_name_salary_mean,2.055959e+16
489,schedule_name_is_Гибкий график employer_id_id_count,1.979007e+16
33,salary_currency_id_count,1.966936e+16
201,employment_name_is_Частичная занятость experience_name_is_От 3 до 6 лет,1.830126e+16
368,experience_name_is_От 3 до 6 лет experience_name_salary_mean,1.821928e+16
576,employment_name_salary_mean experience_name_salary_mean,1.803732e+16
210,employment_name_is_Частичная занятость schedule_name_is_Удаленная работа,1.794055e+16
358,experience_name_is_От 3 до 6 лет salary_currency_is_USD,1.788717e+16
237,employment_name_is_Полная занятость schedule_name_is_Сменный график,1.780239e+16
315,experience_name_is_Нет опыта schedule_name_is_Сменный график,1.665163e+16
621,employment_name_id_count experience_name_id_count,1.652705e+16
45,latitude experience_name_is_От 1 года до 3 лет,1.651064e+16
115,population salary_currency_is_USD,1.604947e+16
629,schedule_name_id_count^2,1.603291e+16
22,schedule_name_is_Вахтовый метод,1.600155e+16
223,employment_name_is_Частичная занятость schedule_name_id_count,1.599391e+16
44,latitude experience_name_is_Нет опыта,1.582183e+16
624,experience_name_id_count^2,1.563577e+16
563,area_name_salary_mean schedule_name_id_count,1.435053e+16
392,experience_name_is_Более 6 лет schedule_name_salary_mean,1.424085e+16
25,employment_name_salary_mean,1.393064e+16
369,experience_name_is_От 3 до 6 лет salary_currency_salary_mean,1.370866e+16
327,experience_name_is_Нет опыта experience_name_id_count,1.321771e+16
240,employment_name_is_Полная занятость area_name_salary_mean,1.314323e+16
242,employment_name_is_Полная занятость employment_name_salary_mean,1.289072e+16
248,employment_name_is_Полная занятость employment_name_id_count,1.289072e+16
224,employment_name_is_Полная занятость^2,1.289072e+16
215,employment_name_is_Частичная занятость experience_name_salary_mean,1.283000e+16
14,salary_currency_is_RUR,1.246587e+16
109,population experience_name_is_Нет опыта,1.208056e+16
126,population salary_currency_salary_mean,1.202938e+16
208,employment_name_is_Частичная занятость schedule_name_is_Полный день,1.182146e+16
501,schedule_name_is_Полный день experience_name_salary_mean,1.177822e+16
382,experience_name_is_Более 6 лет schedule_name_is_Гибкий график,1.167483e+16
163,distance_to_Moscow salary_currency_id_count,1.141273e+16
604,schedule_name_salary_mean employer_id_id_count,1.127198e+16
281,employment_name_is_Проектная работа experience_name_is_От 1 года до 3 лет,1.113523e+16
304,employment_name_is_Проектная работа schedule_name_id_count,1.095599e+16
222,employment_name_is_Частичная занятость salary_currency_id_count,1.046543e+16
490,schedule_name_is_Гибкий график employment_name_id_count,1.045388e+16
16,salary_currency_is_USD,1.041904e+16
108,population employment_name_is_Проектная работа,1.011398e+16
397,experience_name_is_Более 6 лет salary_currency_id_count,1.003229e+16
557,area_name_salary_mean schedule_name_salary_mean,1.001930e+16
566,employer_id_salary_mean experience_name_salary_mean,9.889440e+15
112,population experience_name_is_Более 6 лет,9.843532e+15
111,population experience_name_is_От 3 до 6 лет,9.762500e+15
443,salary_currency_is_USD schedule_name_is_Полный день,9.281966e+15
65,latitude employment_name_id_count,9.159641e+15
9,employment_name_is_Проектная работа,8.897438e+15
43,latitude employment_name_is_Проектная работа,8.391143e+15
49,latitude salary_currency_is_EUR,8.282803e+15
195,employment_name_is_Частичная занятость^2,8.183060e+15
203,employment_name_is_Частичная занятость salary_currency_is_RUR,8.183060e+15
42,latitude employment_name_is_Стажировка,8.120286e+15
48,latitude salary_currency_is_RUR,7.730207e+15
586,experience_name_salary_mean salary_currency_salary_mean,6.927123e+15
357,experience_name_is_От 3 до 6 лет salary_currency_is_EUR,6.877100e+15
263,employment_name_is_Стажировка schedule_name_is_Полный день,6.745723e+15
572,employer_id_salary_mean experience_name_id_count,6.670330e+15
62,latitude schedule_name_salary_mean,6.596275e+15
335,experience_name_is_От 1 года до 3 лет salary_currency_is_USD,6.503454e+15
278,employment_name_is_Стажировка schedule_name_id_count,6.434897e+15
279,employment_name_is_Проектная работа^2,6.130216e+15
284,employment_name_is_Проектная работа salary_currency_is_RUR,6.130216e+15
110,population experience_name_is_От 1 года до 3 лет,6.120707e+15
303,employment_name_is_Проектная работа salary_currency_id_count,6.055708e+15
445,salary_currency_is_USD schedule_name_is_Удаленная работа,5.978578e+15
40,latitude employment_name_is_Частичная занятость,5.790553e+15
255,employment_name_is_Стажировка experience_name_is_От 1 года до 3 лет,5.764134e+15
531,schedule_name_is_Удаленная работа salary_currency_salary_mean,5.704781e+15
424,salary_currency_is_EUR schedule_name_is_Полный день,5.513166e+15
499,schedule_name_is_Полный день employer_id_salary_mean,5.487586e+15
296,employment_name_is_Проектная работа experience_name_salary_mean,5.370321e+15
74,longitude employment_name_is_Полная занятость,5.200089e+15
426,salary_currency_is_EUR schedule_name_is_Удаленная работа,4.974799e+15
114,population salary_currency_is_EUR,4.904381e+15
502,schedule_name_is_Полный день salary_currency_salary_mean,4.753201e+15
27,salary_currency_salary_mean,4.668590e+15
319,experience_name_is_Нет опыта employer_id_salary_mean,4.659891e+15
506,schedule_name_is_Полный день employment_name_id_count,4.590761e+15
591,experience_name_salary_mean experience_name_id_count,4.461097e+15
298,employment_name_is_Проектная работа schedule_name_salary_mean,4.341473e+15
31,employment_name_id_count,4.287802e+15
95,longitude schedule_name_salary_mean,4.223828e+15
80,longitude experience_name_is_Более 6 лет,4.175551e+15
450,salary_currency_is_USD experience_name_salary_mean,4.139597e+15
191,key_skills_count employment_name_id_count,4.135869e+15
341,experience_name_is_От 1 года до 3 лет schedule_name_is_Вахтовый метод,4.134655e+15
549,schedule_name_is_Вахтовый метод experience_name_id_count,4.134655e+15
542,schedule_name_is_Вахтовый метод employment_name_salary_mean,4.134655e+15
407,salary_currency_is_RUR schedule_name_is_Вахтовый метод,4.134655e+15
239,employment_name_is_Полная занятость schedule_name_is_Вахтовый метод,4.134655e+15
546,schedule_name_is_Вахтовый метод area_name_id_count,4.134655e+15
548,schedule_name_is_Вахтовый метод employment_name_id_count,4.134655e+15
539,schedule_name_is_Вахтовый метод^2,4.134655e+15
458,salary_currency_is_USD schedule_name_id_count,4.054913e+15
121,population schedule_name_is_Вахтовый метод,4.023344e+15
620,employment_name_id_count^2,3.973106e+15
105,population employment_name_is_Частичная занятость,3.871235e+15
326,experience_name_is_Нет опыта employment_name_id_count,3.747252e+15
583,employment_name_salary_mean salary_currency_id_count,3.723833e+15
451,salary_currency_is_USD salary_currency_salary_mean,3.624470e+15
550,schedule_name_is_Вахтовый метод salary_currency_id_count,3.559537e+15
627,salary_currency_id_count^2,3.384212e+15
545,schedule_name_is_Вахтовый метод schedule_name_salary_mean,3.333010e+15
241,employment_name_is_Полная занятость employer_id_salary_mean,3.275842e+15
46,latitude experience_name_is_От 3 до 6 лет,3.255434e+15
483,schedule_name_is_Гибкий график employer_id_salary_mean,3.183767e+15
343,experience_name_is_От 1 года до 3 лет employer_id_salary_mean,3.179896e+15
537,schedule_name_is_Удаленная работа salary_currency_id_count,2.967193e+15
207,employment_name_is_Частичная занятость schedule_name_is_Гибкий график,2.961864e+15
473,salary_currency_is_UAH employment_name_id_count,2.942150e+15
459,salary_currency_is_UAH^2,2.942150e+15
467,salary_currency_is_UAH employment_name_salary_mean,2.942150e+15
234,employment_name_is_Полная занятость salary_currency_is_UAH,2.942150e+15
359,experience_name_is_От 3 до 6 лет salary_currency_is_UAH,2.942150e+15
463,salary_currency_is_UAH schedule_name_is_Удаленная работа,2.942150e+15
565,employer_id_salary_mean employment_name_salary_mean,2.899413e+15
540,schedule_name_is_Вахтовый метод area_name_salary_mean,2.775562e+15
361,experience_name_is_От 3 до 6 лет schedule_name_is_Полный день,2.751925e+15
374,experience_name_is_От 3 до 6 лет experience_name_id_count,2.692796e+15
246,employment_name_is_Полная занятость area_name_id_count,2.680328e+15
79,longitude experience_name_is_От 3 до 6 лет,2.659276e+15
120,population schedule_name_is_Удаленная работа,2.319980e+15
56,latitude schedule_name_is_Вахтовый метод,2.242962e+15
366,experience_name_is_От 3 до 6 лет employer_id_salary_mean,2.054860e+15
282,employment_name_is_Проектная работа experience_name_is_От 3 до 6 лет,2.039263e+15
276,employment_name_is_Стажировка experience_name_id_count,1.918246e+15
579,employment_name_salary_mean area_name_id_count,1.812306e+15
518,schedule_name_is_Сменный график schedule_name_salary_mean,1.726828e+15
60,latitude experience_name_salary_mean,1.675002e+15
84,longitude salary_currency_is_UAH,1.615492e+15
55,latitude schedule_name_is_Удаленная работа,1.576247e+15
293,employment_name_is_Проектная работа area_name_salary_mean,1.569341e+15
468,salary_currency_is_UAH experience_name_salary_mean,1.492217e+15
51,latitude salary_currency_is_UAH,1.447697e+15
599,salary_currency_salary_mean experience_name_id_count,1.442963e+15
431,salary_currency_is_EUR experience_name_salary_mean,1.362830e+15
346,experience_name_is_От 1 года до 3 лет salary_currency_salary_mean,1.332700e+15
41,latitude employment_name_is_Полная занятость,1.313079e+15
15,salary_currency_is_EUR,1.282628e+15
465,salary_currency_is_UAH area_name_salary_mean,1.167563e+15
577,employment_name_salary_mean salary_currency_salary_mean,1.163088e+15
598,salary_currency_salary_mean employment_name_id_count,1.163088e+15
244,employment_name_is_Полная занятость salary_currency_salary_mean,1.163088e+15
350,experience_name_is_От 1 года до 3 лет employment_name_id_count,1.134391e+15
388,experience_name_is_Более 6 лет employer_id_salary_mean,1.111127e+15
541,schedule_name_is_Вахтовый метод employer_id_salary_mean,1.084205e+15
437,salary_currency_is_EUR experience_name_id_count,1.004024e+15
82,longitude salary_currency_is_EUR,9.704056e+14
469,salary_currency_is_UAH salary_currency_salary_mean,9.466383e+14
474,salary_currency_is_UAH experience_name_id_count,8.327002e+14
116,population salary_currency_is_UAH,7.738969e+14
213,employment_name_is_Частичная занятость employer_id_salary_mean,7.713939e+14
54,latitude schedule_name_is_Сменный график,7.587064e+14
149,distance_to_Moscow schedule_name_is_Полный день,6.472365e+14
434,salary_currency_is_EUR area_name_id_count,5.785457e+14
270,employment_name_is_Стажировка experience_name_salary_mean,5.729903e+14
409,salary_currency_is_RUR employer_id_salary_mean,5.558623e+14
471,salary_currency_is_UAH area_name_id_count,5.313533e+14
147,distance_to_Moscow salary_currency_is_UAH,4.505607e+14
220,employment_name_is_Частичная занятость employment_name_id_count,3.801011e+14
543,schedule_name_is_Вахтовый метод experience_name_salary_mean,3.545874e+14
476,salary_currency_is_UAH schedule_name_id_count,3.490804e+14
466,salary_currency_is_UAH employer_id_salary_mean,3.290446e+14
410,salary_currency_is_RUR employment_name_salary_mean,3.036770e+14
78,longitude experience_name_is_От 1 года до 3 лет,2.898749e+14
393,experience_name_is_Более 6 лет area_name_id_count,2.502871e+14
277,employment_name_is_Стажировка salary_currency_id_count,1.942037e+14
152,distance_to_Moscow schedule_name_is_Вахтовый метод,1.447111e+14
146,distance_to_Moscow salary_currency_is_USD,4.489626e+13
177,key_skills_count salary_currency_is_UAH,2.105748e+13
472,salary_currency_is_UAH employer_id_id_count,1.843499e+13
0,1,1.742562e+13
182,key_skills_count schedule_name_is_Вахтовый метод,8.113807e+12
438,salary_currency_is_EUR salary_currency_id_count,5.072049e+12
547,schedule_name_is_Вахтовый метод employer_id_id_count,2.381823e+12
609,area_name_id_count^2,1.113108e+06
103,population distance_to_Moscow,9.128232e+05
96,longitude area_name_id_count,7.032085e+05
123,population employer_id_salary_mean,6.317245e+05
102,population^2,4.537460e+05
190,key_skills_count employer_id_id_count,3.491204e+05
37,latitude population,2.757345e+05
553,area_name_salary_mean employer_id_salary_mean,1.587812e+05
122,population area_name_salary_mean,1.327850e+05
91,longitude employer_id_salary_mean,1.289066e+05
184,key_skills_count employer_id_salary_mean,9.156431e+04
153,distance_to_Moscow area_name_salary_mean,8.965900e+04
189,key_skills_count area_name_id_count,7.550875e+04
129,population employer_id_id_count,6.602900e+04
134,distance_to_Moscow^2,4.189919e+04
559,area_name_salary_mean employer_id_id_count,3.974650e+04
160,distance_to_Moscow employer_id_id_count,3.580275e+04
564,employer_id_salary_mean^2,2.897712e+04
135,distance_to_Moscow key_skills_count,1.519303e+04
39,latitude key_skills_count,1.494500e+04
57,latitude area_name_salary_mean,1.222750e+04
71,longitude distance_to_Moscow,1.137825e+04
64,latitude employer_id_id_count,7.379000e+03
615,employer_id_id_count^2,5.808000e+03
38,latitude distance_to_Moscow,4.368406e+03
72,longitude key_skills_count,3.789375e+03
165,key_skills_count^2,3.127000e+03
198,employment_name_is_Частичная занятость employment_name_is_Проектная работа,2.080000e+02
204,employment_name_is_Частичная занятость salary_currency_is_EUR,1.280000e+02
421,salary_currency_is_EUR salary_currency_is_USD,0.000000e+00
475,salary_currency_is_UAH salary_currency_id_count,0.000000e+00
332,experience_name_is_От 1 года до 3 лет experience_name_is_Более 6 лет,0.000000e+00
331,experience_name_is_От 1 года до 3 лет experience_name_is_От 3 до 6 лет,0.000000e+00
478,schedule_name_is_Гибкий график schedule_name_is_Полный день,0.000000e+00
444,salary_currency_is_USD schedule_name_is_Сменный график,0.000000e+00
446,salary_currency_is_USD schedule_name_is_Вахтовый метод,0.000000e+00
462,salary_currency_is_UAH schedule_name_is_Сменный график,0.000000e+00
386,experience_name_is_Более 6 лет schedule_name_is_Вахтовый метод,0.000000e+00
511,schedule_name_is_Сменный график schedule_name_is_Удаленная работа,0.000000e+00
461,salary_currency_is_UAH schedule_name_is_Полный день,0.000000e+00
512,schedule_name_is_Сменный график schedule_name_is_Вахтовый метод,0.000000e+00
464,salary_currency_is_UAH schedule_name_is_Вахтовый метод,0.000000e+00
517,schedule_name_is_Сменный график salary_currency_salary_mean,0.000000e+00
321,experience_name_is_Нет опыта experience_name_salary_mean,0.000000e+00
460,salary_currency_is_UAH schedule_name_is_Гибкий график,0.000000e+00
317,experience_name_is_Нет опыта schedule_name_is_Вахтовый метод,0.000000e+00
381,experience_name_is_Более 6 лет salary_currency_is_UAH,0.000000e+00
310,experience_name_is_Нет опыта salary_currency_is_EUR,0.000000e+00
396,experience_name_is_Более 6 лет experience_name_id_count,0.000000e+00
441,salary_currency_is_USD salary_currency_is_UAH,0.000000e+00
336,experience_name_is_От 1 года до 3 лет salary_currency_is_UAH,0.000000e+00
496,schedule_name_is_Полный день schedule_name_is_Удаленная работа,0.000000e+00
481,schedule_name_is_Гибкий график schedule_name_is_Вахтовый метод,0.000000e+00
422,salary_currency_is_EUR salary_currency_is_UAH,0.000000e+00
423,salary_currency_is_EUR schedule_name_is_Гибкий график,0.000000e+00
425,salary_currency_is_EUR schedule_name_is_Сменный график,0.000000e+00
427,salary_currency_is_EUR schedule_name_is_Вахтовый метод,0.000000e+00
355,experience_name_is_От 3 до 6 лет experience_name_is_Более 6 лет,0.000000e+00
384,experience_name_is_Более 6 лет schedule_name_is_Сменный график,0.000000e+00
495,schedule_name_is_Полный день schedule_name_is_Сменный график,0.000000e+00
480,schedule_name_is_Гибкий график schedule_name_is_Удаленная работа,0.000000e+00
364,experience_name_is_От 3 до 6 лет schedule_name_is_Вахтовый метод,0.000000e+00
412,salary_currency_is_RUR salary_currency_salary_mean,0.000000e+00
497,schedule_name_is_Полный день schedule_name_is_Вахтовый метод,0.000000e+00
470,salary_currency_is_UAH schedule_name_salary_mean,0.000000e+00
402,salary_currency_is_RUR salary_currency_is_UAH,0.000000e+00